### ISSUE TITLE
Installed hardware internet Radio and now

### ISSUE THREAD

**Issue by delmeer** [JackV2020/Domoticz-InternetRadio#1]
Hi Jack,
Installed the plugin, added Internet Radio to hardware ans now....
How do I get the radio visible in domoticz?
Martijn

**Comment by JackV2020** [comment]
Hi Martijn,

Nice to hear from you. Not so nice you have an issue.😬
I will try to help you out.

It should be possible to find a dropdown box on the dashboard page, the top right corner. There you should be able to select the internet radio. 
When it not there, do you see messages in the logging?
Did you install the things mentioned in github like the, I think, requests module and mplayer?
Note that the config file is old and you may want to edit it.

I hope this helps. Please let me know.

Kind regards,

Jack

⁣BlueMail voor Android downloaden ​

Op 17 dec. 2021 11:29, om 11:29, delmeer ***@***.***> schreef:

**Comment by delmeer** [comment]
Hoi Jack,

Aan je achternaam te zien kom je uit Nederland. 
Dank voor je snelle reactie!!

Heb je handleiding gevolgd maar komt geen “room” bij voor de internet radio. 
Kan hem wel bij hardware toevoegen. 

Draai het op een test systeem dus zal maandag nog eens proberen of het dan wel lukt. 

Zijn er naast de streams nog andere parameters in de config die ik aan moet passen?
Moet namelijk bekeken dat ik er niet echt goed in gekeken heb😬

Groet, Martijn

Sent from mobile device, apologies for typos


Op 17 dec. 2021 om 11:56 heeft Jack Veraart ***@***.***> het volgende geschreven:

﻿
Hi Martijn,

Nice to hear from you. Not so nice you have an issue.😬
I will try to help you out.

It should be possible to find a dropdown box on the dashboard page, the top right corner. There you should be able to select the internet radio. 
When it not there, do you see messages in the logging?
Did you install the things mentioned in github like the, I think, requests module and mplayer?
Note that the config file is old and you may want to edit it.

I hope this helps. Please let me know.

Kind regards,

Jack

⁣BlueMail voor Android downloaden ​

Op 17 dec. 2021 11:29, om 11:29, delmeer ***@***.***> schreef:
>Hi Jack,
>Installed the plugin, added Internet Radio to hardware ans now....
>How do I get the radio visible in domoticz?
>Martijn
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/JackV2020/Domoticz-InternetRadio/issues/1
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by delmeer** [comment]
Hi Jack,

 

Start all over again, let’s see what happens this time.

 

Clean install of Buster and Domoticz 2021.1

 
sudo apt-get install python3-requests
Reading package lists... Done
Building dependency tree       

Reading state information... Done

python3-requests is already the newest version (2.21.0-1).

python3-requests set to manually installed.

The following packages were automatically installed and are no longer required:

  libappstream-glib8 libostree-1-1 p11-kit p11-kit-modules

Use 'sudo apt autoremove' to remove them.

0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
sudo apt install mplayer
Reading package lists... Done
Building dependency tree       

Reading state information... Done

The following packages were automatically installed and are no longer required:

  libappstream-glib8 libostree-1-1 p11-kit p11-kit-modules

Use 'sudo apt autoremove' to remove them.

The following additional packages will be installed:

  libaudio2 libdirectfb-1.7-7 libenca0 libvorbisidec1 libxvmc1

Suggested packages:

  nas libdirectfb-extra mplayer-doc netselect | fping

The following NEW packages will be installed:

  libaudio2 libdirectfb-1.7-7 libenca0 libvorbisidec1 libxvmc1 mplayer

0 upgraded, 6 newly installed, 0 to remove and 10 not upgraded.

Need to get 3,164 kB of archives.

After this operation, 7,935 kB of additional disk space will be used.

Do you want to continue? [Y/n] y

Get:1 http://mirror.serverius.net/raspbian/raspbian buster/main armhf libaudio2 armhf 1.9.4-6 [72.7 kB]

Get:2 http://mirror.serverius.net/raspbian/raspbian buster/main armhf libdirectfb-1.7-7 armhf 1.7.7-9 [934 kB]

Get:3 http://mirror.serverius.net/raspbian/raspbian buster/main armhf libenca0 armhf 1.19-1 [55.3 kB]

Get:4 http://mirror.serverius.net/raspbian/raspbian buster/main armhf libvorbisidec1 armhf 1.2.1+git20180316-3 [66.2 kB]

Get:5 http://mirror.serverius.net/raspbian/raspbian buster/main armhf libxvmc1 armhf 2:1.0.10-1 [24.5 kB]

Get:6 http://mirror.serverius.net/raspbian/raspbian buster/main armhf mplayer armhf 2:1.3.0-8+b5 [2,012 kB]

Fetched 3,164 kB in 4s (867 kB/s)     

Selecting previously unselected package libaudio2:armhf.

(Reading database ... 162827 files and directories currently installed.)

Preparing to unpack .../0-libaudio2_1.9.4-6_armhf.deb ...

Unpacking libaudio2:armhf (1.9.4-6) ...

Selecting previously unselected package libdirectfb-1.7-7:armhf.

Preparing to unpack .../1-libdirectfb-1.7-7_1.7.7-9_armhf.deb ...

Unpacking libdirectfb-1.7-7:armhf (1.7.7-9) ...

Selecting previously unselected package libenca0:armhf.

Preparing to unpack .../2-libenca0_1.19-1_armhf.deb ...

Unpacking libenca0:armhf (1.19-1) ...

Selecting previously unselected package libvorbisidec1.

Preparing to unpack .../3-libvorbisidec1_1.2.1+git20180316-3_armhf.deb ...

Unpacking libvorbisidec1 (1.2.1+git20180316-3) ...

Selecting previously unselected package libxvmc1:armhf.

Preparing to unpack .../4-libxvmc1_2%3a1.0.10-1_armhf.deb ...

Unpacking libxvmc1:armhf (2:1.0.10-1) ...

Selecting previously unselected package mplayer.

Preparing to unpack .../5-mplayer_2%3a1.3.0-8+b5_armhf.deb ...

Unpacking mplayer (2:1.3.0-8+b5) ...

Setting up libvorbisidec1 (1.2.1+git20180316-3) ...

Setting up libenca0:armhf (1.19-1) ...

Setting up libxvmc1:armhf (2:1.0.10-1) ...

Setting up libaudio2:armhf (1.9.4-6) ...

Setting up libdirectfb-1.7-7:armhf (1.7.7-9) ...

Setting up mplayer (2:1.3.0-8+b5) ...

Processing triggers for libc-bin (2.28-10+rpt2+rpi1) ...

Processing triggers for man-db (2.8.5-2) ...

Processing triggers for mime-support (3.62) ...
sudo reboot -h. now
cd domoticz/plugins
git clone https://github.com/JackV2020/Domoticz-InternetRadio.git internetradio
Cloning into 'internetradio'...

remote: Enumerating objects: 33, done.

remote: Counting objects: 100% (33/33), done.

remote: Compressing objects: 100% (31/31), done.

remote: Total 33 (delta 3), reused 32 (delta 2), pack-reused 0

Unpacking objects: 100% (33/33), done.
sudo reboot -h now
“After this you can add a device of the Type 'Jacks Internet Radio'.” I add a “Hardware device” Jacks Internet Radio. Called it Internet Radio.
Left username and password unchanged. Probably this is where it went wrong last time😬 I think it’s only necessary when adding so the room can be created. After that you can enable a user/pass again.
 

Whoop Whoop, all works fine!! Audio is default set to HDMI. Luckily, I installed Buster with desktop so that’s easy to change to mini jack.

 

Best wishes, 

Martijn

 

Van: Jack Veraart ***@***.***>
Beantwoorden - Aan: JackV2020/Domoticz-InternetRadio ***@***.***>
Datum: vrijdag 17 december 2021 om 11:56
Aan: JackV2020/Domoticz-InternetRadio ***@***.***>
CC: ***@***.***" ***@***.***>, Author ***@***.***>
Onderwerp: Re: [JackV2020/Domoticz-InternetRadio] Installed hardware internet Radio and now (Issue #1)

 

Hi Martijn,

Nice to hear from you. Not so nice you have an issue.😬
I will try to help you out.

It should be possible to find a dropdown box on the dashboard page, the top right corner. There you should be able to select the internet radio. 
When it not there, do you see messages in the logging?
Did you install the things mentioned in github like the, I think, requests module and mplayer?
Note that the config file is old and you may want to edit it.

I hope this helps. Please let me know.

Kind regards,

Jack

⁣BlueMail voor Android downloaden ​

Op 17 dec. 2021 11:29, om 11:29, delmeer ***@***.***> schreef:
>Hi Jack,
>Installed the plugin, added Internet Radio to hardware ans now....
>How do I get the radio visible in domoticz?
>Martijn
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/JackV2020/Domoticz-InternetRadio/issues/1
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>


—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JackV2020** [comment]
Hi Martijn,

I am glad to hear that things work now.😀👍
On the hardware page there is a remark concerning username and password when you have users. Maybe you missed that. 
Note.....When you make changes to the config file like changing url's, extra buttons, extra stations, remove stations  or whatever and restart the plugin, it wants to recreate the room.
Also fun is the scrolling marquee in the status "button". When you click on that while using a browser on your phone, your phone  will connect to the station too😊
In the Favorieten is a 'channel' named Sssst which kills all mplayer processes.

Kind regards, happy Hollidays an enjoy the music

Jack

⁣BlueMail voor Android downloaden ​

Op 20 dec. 2021 14:10, om 14:10, delmeer ***@***.***> schreef:
>Hi Jack,
>
> 
>
>Start all over again, let’s see what happens this time.
>
> 
>
>Clean install of Buster and Domoticz 2021.1
>
> 
>sudo apt-get install python3-requests
>Reading package lists... Done
>Building dependency tree       
>
>Reading state information... Done
>
>python3-requests is already the newest version (2.21.0-1).
>
>python3-requests set to manually installed.
>
>The following packages were automatically installed and are no longer
>required:
>
>  libappstream-glib8 libostree-1-1 p11-kit p11-kit-modules
>
>Use 'sudo apt autoremove' to remove them.
>
>0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
>sudo apt install mplayer
>Reading package lists... Done
>Building dependency tree       
>
>Reading state information... Done
>
>The following packages were automatically installed and are no longer
>required:
>
>  libappstream-glib8 libostree-1-1 p11-kit p11-kit-modules
>
>Use 'sudo apt autoremove' to remove them.
>
>The following additional packages will be installed:
>
>  libaudio2 libdirectfb-1.7-7 libenca0 libvorbisidec1 libxvmc1
>
>Suggested packages:
>
>  nas libdirectfb-extra mplayer-doc netselect | fping
>
>The following NEW packages will be installed:
>
>  libaudio2 libdirectfb-1.7-7 libenca0 libvorbisidec1 libxvmc1 mplayer
>
>0 upgraded, 6 newly installed, 0 to remove and 10 not upgraded.
>
>Need to get 3,164 kB of archives.
>
>After this operation, 7,935 kB of additional disk space will be used.
>
>Do you want to continue? [Y/n] y
>
>Get:1 http://mirror.serverius.net/raspbian/raspbian buster/main armhf
>libaudio2 armhf 1.9.4-6 [72.7 kB]
>
>Get:2 http://mirror.serverius.net/raspbian/raspbian buster/main armhf
>libdirectfb-1.7-7 armhf 1.7.7-9 [934 kB]
>
>Get:3 http://mirror.serverius.net/raspbian/raspbian buster/main armhf
>libenca0 armhf 1.19-1 [55.3 kB]
>
>Get:4 http://mirror.serverius.net/raspbian/raspbian buster/main armhf
>libvorbisidec1 armhf 1.2.1+git20180316-3 [66.2 kB]
>
>Get:5 http://mirror.serverius.net/raspbian/raspbian buster/main armhf
>libxvmc1 armhf 2:1.0.10-1 [24.5 kB]
>
>Get:6 http://mirror.serverius.net/raspbian/raspbian buster/main armhf
>mplayer armhf 2:1.3.0-8+b5 [2,012 kB]
>
>Fetched 3,164 kB in 4s (867 kB/s)     
>
>Selecting previously unselected package libaudio2:armhf.
>
>(Reading database ... 162827 files and directories currently
>installed.)
>
>Preparing to unpack .../0-libaudio2_1.9.4-6_armhf.deb ...
>
>Unpacking libaudio2:armhf (1.9.4-6) ...
>
>Selecting previously unselected package libdirectfb-1.7-7:armhf.
>
>Preparing to unpack .../1-libdirectfb-1.7-7_1.7.7-9_armhf.deb ...
>
>Unpacking libdirectfb-1.7-7:armhf (1.7.7-9) ...
>
>Selecting previously unselected package libenca0:armhf.
>
>Preparing to unpack .../2-libenca0_1.19-1_armhf.deb ...
>
>Unpacking libenca0:armhf (1.19-1) ...
>
>Selecting previously unselected package libvorbisidec1.
>
>Preparing to unpack .../3-libvorbisidec1_1.2.1+git20180316-3_armhf.deb
>...
>
>Unpacking libvorbisidec1 (1.2.1+git20180316-3) ...
>
>Selecting previously unselected package libxvmc1:armhf.
>
>Preparing to unpack .../4-libxvmc1_2%3a1.0.10-1_armhf.deb ...
>
>Unpacking libxvmc1:armhf (2:1.0.10-1) ...
>
>Selecting previously unselected package mplayer.
>
>Preparing to unpack .../5-mplayer_2%3a1.3.0-8+b5_armhf.deb ...
>
>Unpacking mplayer (2:1.3.0-8+b5) ...
>
>Setting up libvorbisidec1 (1.2.1+git20180316-3) ...
>
>Setting up libenca0:armhf (1.19-1) ...
>
>Setting up libxvmc1:armhf (2:1.0.10-1) ...
>
>Setting up libaudio2:armhf (1.9.4-6) ...
>
>Setting up libdirectfb-1.7-7:armhf (1.7.7-9) ...
>
>Setting up mplayer (2:1.3.0-8+b5) ...
>
>Processing triggers for libc-bin (2.28-10+rpt2+rpi1) ...
>
>Processing triggers for man-db (2.8.5-2) ...
>
>Processing triggers for mime-support (3.62) ...
>sudo reboot -h. now
>cd domoticz/plugins
>git clone https://github.com/JackV2020/Domoticz-InternetRadio.git
>internetradio
>Cloning into 'internetradio'...
>
>remote: Enumerating objects: 33, done.
>
>remote: Counting objects: 100% (33/33), done.
>
>remote: Compressing objects: 100% (31/31), done.
>
>remote: Total 33 (delta 3), reused 32 (delta 2), pack-reused 0
>
>Unpacking objects: 100% (33/33), done.
>sudo reboot -h now
>“After this you can add a device of the Type 'Jacks Internet Radio'.” I
>add a “Hardware device” Jacks Internet Radio. Called it Internet
>Radio.
>Left username and password unchanged. Probably this is where it went
>wrong last time😬 I think it’s only necessary when adding so the room
>can be created. After that you can enable a user/pass again.
> 
>
>Whoop Whoop, all works fine!! Audio is default set to HDMI. Luckily, I
>installed Buster with desktop so that’s easy to change to mini jack.
>
> 
>
>Best wishes, 
>
>Martijn
>
> 
>
>Van: Jack Veraart ***@***.***>
>Beantwoorden - Aan: JackV2020/Domoticz-InternetRadio ***@***.***>
>Datum: vrijdag 17 december 2021 om 11:56
>Aan: JackV2020/Domoticz-InternetRadio ***@***.***>
>CC: ***@***.***" ***@***.***>, Author ***@***.***>
>Onderwerp: Re: [JackV2020/Domoticz-InternetRadio] Installed hardware
>internet Radio and now (Issue #1)
>
> 
>
>Hi Martijn,
>
>Nice to hear from you. Not so nice you have an issue.😬
>I will try to help you out.
>
>It should be possible to find a dropdown box on the dashboard page, the
>top right corner. There you should be able to select the internet
>radio. 
>When it not there, do you see messages in the logging?
>Did you install the things mentioned in github like the, I think,
>requests module and mplayer?
>Note that the config file is old and you may want to edit it.
>
>I hope this helps. Please let me know.
>
>Kind regards,
>
>Jack
>
>⁣BlueMail voor Android downloaden ​
>
>Op 17 dec. 2021 11:29, om 11:29, delmeer ***@***.***> schreef:
>>Hi Jack,
>>Installed the plugin, added Internet Radio to hardware ans now....
>>How do I get the radio visible in domoticz?
>>Martijn
>>
>>-- 
>>Reply to this email directly or view it on GitHub:
>>https://github.com/JackV2020/Domoticz-InternetRadio/issues/1
>>You are receiving this because you are subscribed to this thread.
>>
>>Message ID: ***@***.***>
>
>
>—
>Reply to this email directly, view it on GitHub, or unsubscribe.
>Triage notifications on the go with GitHub Mobile for iOS or Android. 
>You are receiving this because you authored the thread.Message ID:
>***@***.***>
>
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/JackV2020/Domoticz-InternetRadio/issues/1#issuecomment-997910604
>You are receiving this because you commented.
>
>Message ID:
***@***.***>
